openapi: 3.0.3
info:
  version: 1.0.0
  title: Ikioma payments API-spec

security:
  - bearerAuth: []

paths:
  /v1/system/ping:
    get:
      operationId: ping
      summary: Replies with pong
      description: Replies ping with pong
      tags:
        - System
      responses:
        "200":
          description: Pong
          content:
            text/plain:
              schema:
                type: string

  /v1/prescriptionRenewal:
    post:
      summary:  Creates prescription renewal 
      description: Creates an prescription renewal
      operationId: createPrescriptionRenewal
      tags:
        - PrescriptionRenewals
      requestBody:
        description: Prescription renewal request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PrescriptionRenewal'
      responses:
        "200":
          description: Created prescription renewal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrescriptionRenewal'
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/prescriptionRenewal/{id}:
    get:
      summary: Find prescription renewal
      description: Finds prescription renewal
      operationId: getPrescriptionRenewal
      tags:
        - PrescriptionRenewals
      parameters:
        - name: id
          in: path
          required: true
          description: Prescription renewal ID
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: Prescription renewal
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PrescriptionRenewal'
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/checkoutFinland/success:
    get:
      summary: Callback endpoint for checkout finland payment success
      description: Callback endpoint for checkout finland payment success
      operationId: checkoutFinlandSuccess
      tags:
        - CheckoutFinland
      parameters:
        - name: checkout-account
          in: query
          required: true
          schema:
            type: integer
            format: int32
            description: Checkout account ID
        - name: checkout-algorithm
          in: query
          required: true
          schema:
            type: string
            description: Used signature algorithm. The same as used by merchant when creating the payment.
        - name: checkout-amount
          in: query
          required: true
          schema:
            type: integer
            format: int32
            description: Payment amount in currency minor unit, e.g. cents
        - name: checkout-stamp
          in: query
          required: true
          schema:
            type: string
            description: Merchant provided stamp
        - name: checkout-reference
          in: query
          required: true
          schema:
            type: string
            description: Merchant provided reference
        - name: checkout-transaction-id
          in: query
          required: true
          schema:
            type: string
            description: Checkout provided transaction ID.
        - name: checkout-status
          in: query
          required: true
          schema:
            type: string
            description: Payment status, either ok, pending, delayed, or fail. See statuses section for more information.
        - name: checkout-provider
          in: query
          required: true
          schema:
            type: string
            description: The payment method provider the client used. Current values are documented on providers tab. The values are subject to change without notice.
        - name: signature
          in: query
          required: true
          schema:
            type: string
            description: HMAC signature calculated from other parameter
      responses:
        "202":
          description: Payment was succesful
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /v1/checkoutFinland/cancel:
    get:
      summary: Callback endpoint for checkout finland payment cancel
      description: Callback endpoint for checkout finland payment cancel
      operationId: checkoutFinlandCancel
      tags:
        - CheckoutFinland
      responses:
        "202":
          description: Sending was successful
        "400":
          description: Invalid request was sent to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      description: Error object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string

    PrescriptionRenewal:
      type: object
      description: Prescription renewal object
      required:
        - practitionerUserId
        - prescriptions
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        practitionerUserId:
          type: string
          format: uuid
          description: Practitioner Keycloak ID
        prescriptions:
          type: array
          description: List of prescriptions with description
          items:
            type: string
            description: Prescription with description
        status:
          $ref: '#/components/schemas/PaymentStatus'
        paymentUrl:
          type: string
          description: Checkout Finland payment URL
          readOnly: true
        transactionId:
          type: string
          description: Checkout provided transaction ID.
        stamp:
          type: string
          format: uuid
          description: Unique payment identifier.
        checkoutAccount:
          type: integer
          description: merchant id

    PaymentStatus:
      type: string
      description: Payment status
      readOnly: true
      enum:
        - NOT_PAID
        - PAID
        - CANCELLED